#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 101pong
## File description:
## 101pong
##

import sys
import math
import numpy
import numpy as np
import numpy.linalg as la

class Point():

    __slots__ = ['x', 'y', 'z'] 

    if sys.argv[1] == '-h':
        print('USAGE')
        print('   ./101pong x0 y0 z0 x1 y1 z1 n\n')
        print('DESCRIPTION\n')
        print('   x0  ball abscissa at time t - 1')
        print('   y0  ball ordinate at time t - 1')
        print('   z0  ball altitude at time t - 1')
        print('   x1  ball abscissa at time t')
        print('   y1  ball ordinate at time t')
        print('   z1  ball altitude at time t')
        print('   n   time shift (greater than or equal to zero, integer)')
        sys.exit(0)
        
    else:
        def __init__(self, x, y, z):
            self.x = float(x)
            self.y = float(y)
            self.z = float(z)
        
        def get_velocity(self, p):
            dx = p.x - self.x
            dy = p.y - self.y
            dz = p.z - self.z
            return Point(float(dx),float(dy),float(dz))

        def coordinates_time(self, dv, t:int):
            if isinstance(t, float):
                sys.exit(84)
            if t < 0:
                sys.exit(84)
            x = self.x + dv.x * t
            y = self.y + dv.y * t
            z = self.z + dv.z * t
            return Point(x, y, z)

        def __str__(self):
            return f'({"{0:.2f}".format(self.x)}, {"{0:.2f}".format(self.y)}, {"{0:.2f}".format(self.z)})'

    if len(sys.argv) < 7:
        sys.exit(84)
    if len(sys.argv) > 8:
        sys.exit(84)
    if len(sys.argv) < 1:
        sys.exit(84)
a = Point(float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3]))
b = Point(float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6]))
result = a.x * b.x + a.y * b.y + a.z * b.z
result = result / math.sqrt((a.x**2 + a.y**2 + a.z**2)) + math.sqrt((b.x**2 + b.y**2 + b.z**2))
t = int(sys.argv[7])
velocity = a.get_velocity(b)
coordinates_time = b.coordinates_time(b, t)
print('The velocity vector of the ball is:\n', velocity, sep="")
print('At time t + ',t, ', ball coordinates will be:\n', b.coordinates_time(velocity, t), sep="")
if sys.argv[1] < sys.argv[4]:
    print("The ball won't reach the paddle.")
else:
    print('The incidence angle is:\n', "%.2f" % result,' degrees', sep="")
